spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update