spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create